version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/backend
    environment:
      FLASK_ENV: base
      REDIS_URL: redis
      REDIS_PORT: 6379
  redis:
    image: "redis:alpine"